insert into test.card_rules (game, rules) values ( 'simple addition ==>elevens', 'Cards are valued Ace=1 through Ten=10. Discard face cards in trios with one each jack, queen, king. Discard other cards in pairs with a total value of 11. Discarded cards are replaced from the deck until it empties. Win by discarding everything.');
insert into test.card_rules (game, rules) values ( 'simple addition ==>thirteens', 'Cards are valued Ace=1 through King=13. Discard cards in pairs with a total value of 13. Discarded cards are replaced from the deck until it empties. Win by discarding everything.');
insert into test.card_rules (game, rules) values ( 'simple addition ==>tens', 'Cards are valued Ace=1 thought Nine=9. Discards tens and face cards in quartets of the same suit. Discard other cards in pairs with a total value of 10. Discarded cards are replaced from the deck until it empties. Win by discarding everything.');
insert into test.card_rules (game, rules) values ( 'simple addition ==>fifteens', 'Cards are valued Ace=1 through Nine=9. Discard tens and face cards in quartets of the same suit. Discard other cards in groups of any size with a total value of 15. Win by emptying the draw deck.');
insert into test.card_rules (game, rules) values ( 'block solitaire ==>elevens', 'Cards are valued Ace=1 through Ten = 10.  Cover pairs of numbers totaling eleven from the deck. Face cards cannot be covered. Win by emptying the draw deck. Note: Face cards dealt during setup were moved to the bottom of the deck.');
insert into test.card_rules (game, rules) values ( 'block solitaire ==>tens', 'Cards are valued Ace=1 through Nine=9. Any two face cards can be covered as a pair. Other cards are covered in pairs with a total value of 10. Tens block futher play on that pile. Win by emptying the draw deck.');
insert into test.card_rules (game, rules) values ( 'baroness', 'Cards are valued Ace=1 through King=13. Discard Kings singly and other card in pairs with a total value of 13 from the tops of piles. When there are no further plays, deal atop the five piles (including empty piles). When the deck size is two, reveal the last two cards in separate piles. Win by discarding everything.');
insert into test.card_rules (game, rules) values ( 'fourteen puzzle', 'Cards are valued Ace=1 through King=13.  Discard cards on the top of piles in pairs with a total value of 14. Win by discarding everything.');
insert into test.card_rules (game, rules) values ( 'pyramid', 'Cards are valued Ace=1 through King=13. Discard available kings singly and other available cards in pairs totaling 13. Cards in the pyramid are available if no other card covers them. The top card of the play pile is available. The top card of the draw becomes available when drawn. If the drawn card is not discarded it must be placed on the play pile.  The play pile may be returned as the draw deck without shuffling up to three times when the draw deck is empty. Win by discarding all 52 cards.');
insert into test.card_rules (game, rules) values ( 'nestor', 'Discard uncovered cards in pairs of the same rank. You may reveal a card from the draw deck, but must then immediately select an uncovered card to pair it with or lose the card. Win by emptying the tableau.');
insert into test.card_rules (game, rules) values ( 'monte carlo', 'Discard adjacent cards of the same rank in pairs.  Cards will shift left and to the next higher row to fill holes prior to refilling the grid. Discard all 52 cards to win.');
insert into test.card_rules (game, rules) values ( 'decade', 'Cards are values Ace=1 through Ten=10. Face cards are worth 10.  Discard triplets of adjacent cards whose total value is 10, 20 or 30. Win by discarding all but one card. Note: All cards are considered to be in one continuous row, but are wrapped for space.' );
insert into test.card_rules (game, rules) values ( 'matrimony', 'Select two cards of the same suit or same rank to discard the one or two cards between them.  Win by discarding all but two cards. Note: All cards are considered to be in one continuous row, but are wrapped for space.' );
insert into test.card_rules (game, rules) values ( 'accordian', 'Combine any pile with the pile one or three (but not two) piles to the left if the top cards have the same suit or rank. Win by combining all the cards into one pile. Note: All cards are considered to be in one continuous row, but are wrapped for space.' );
insert into test.card_rules (game, rules) values ( 'golf', 'Cards are ranked Ace=1 through King=13. Cards may be discarded if they are not covered and are one rank higher or one rank lower than the top card of the discard pile. Win by emptying the tableau.');
insert into test.card_rules (game, rules) values ( 'hit or miss', 'Cards are ranked Ace=1 through King=13. Deal cards one at a time, keeping count from 1 to 13 and resetting. If the rank equals the count, click the exposed card to remove it from the game. When the deck is emptied, flip the exposed pile over without shuffling and continue. Win by removing all cards. Lose by going through the deck twice without removing a card. Trying to remove a card when the count does not match is a strike. Three strikes is a loss.')
insert into test.card_rules (game, rules) values ( 'idiot''s delight', 'Cards are ranked Deuce=2 through King=13, Ace=14. If the tops of two piles are of the same suit, remove the lower ranked one from play. The top card of any pile may be moved to any empty pile.  Win by removing everything from play except the Aces and moving each to its own pile.');
insert into test.card_rules (game, rules) values ( 'royal flush', 'Discard from the face-up pile until you get a royal flush card. Flip the others piles in turn and discard until you get another card from that royal flush or the pile empties. After the last pile, stack the piles from right to left and redeal with one less pile. Win if you finish with no cards other than the royal flush. Do not included discarded cards in the redeals.');
insert into test.card_rules (game, rules) values ( 'perpetual motion', 'Deal one to each of four piles.  If all four match, discard them. If there are any pairs, move the right card of the pair atop the left. Repeat until the deck empties, then collect the piles from right to left a flip without shuffling to from a new deck. Win by discarding the deck. Lose by getting the same starting deck twice.');